@extends('layout.app')
@section('content')
    @include('partials.nav')
    @include('partials.header')
    @include('partials.services')
    @include('partials.potfolio')
    @include('partials.about')
    @include('partials.team')
    @include('partials.clients')
    @include('partials.contact')
    @include('partials.footer')
    @include('partials.modal1')
    @include('partials.modal2')
    @include('partials.modal3')
    
@endsection